version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-dify_telegram}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # expose *internal* 5432 on whatever host port you picked
      - "${POSTGRES_HOST_PORT:-5429}:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_HOST_PORT:-6387}:6379"

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      DEBUG: ${APP_DEBUG}
    ports:
      - "${BACKEND_PORT:-8531}:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8531/api/v1}
    env_file: .env
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-3514}:3000"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
